name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
    tags: 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install OMPython semantic_version PyGithub atlassian-python-api pygit2

      - name: Generate package index
        run: |
          test -f rawdata.json
          python updateinfo.py
          python genindex.py

      - uses: actions/upload-artifact@v4
        with:
          name: packageIndex
          if-no-files-found: error
          path: |
            rawdata.json
            index.json
